spring:
  datasource:
#    url: jdbc:h2:file:/data/demo
    url: jdbc:h2:mem:mydb
    username: h2
    password: h2
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect